# -*- coding: utf-8 -*-
"""Remove Numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ac2JxSukc5Pw0Sa2uWVqEdSvbJQdM65G
"""

import pandas as pd
import re

# Load the dataset
df = pd.read_csv('measuring_hate_speech.csv')

# Display the first few rows of the dataset
print("Before Cleaning:")
print(df.head())

def contains_numbers(cell):
    return bool(re.search(r'\d', str(cell)))

# Identify columns with numbers
columns_with_numbers = [col for col in df.columns if any(df[col].apply(contains_numbers))]

# Replace numbers with NaN in identified columns
df[columns_with_numbers] = df[columns_with_numbers].applymap(lambda x: None if contains_numbers(x) else x)

# Drop columns with all null values
df_cleaned = df.dropna(axis=1, how='all')

print("\nAfter Cleaning:")
print(df_cleaned.head())

# Save the cleaned dataset to a new CSV file
# Replace 'cleaned_dataset.csv' with the desired output file name
df.to_csv('cleaned_dataset.csv', index=False)
